
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team01-s26-13
owner: ucsb-cs156-s26
repo_name: team01-s26-13
pull_requests: [{"author":{"id":"MDQ6VXNlcjc5ODYzNTE4","is_bot":false,"login":"rohannihalani","name":"Rohan Nihalani"},"headRefName":"Rohan-DiningCommonsMenuItem-GetSingleRecord","number":53,"title":"Add GET (show) endpoint for a single record in UCSBDiningCommonsMenuItem table","url":"https://github.com/ucsb-cs156-s26/team01-s26-13/pull/53"},{"author":{"id":"MDQ6VXNlcjc5ODYzNTE4","is_bot":false,"login":"rohannihalani","name":"Rohan Nihalani"},"headRefName":"Rohan-DiningCommonsMenuItem-controller","number":52,"title":"Create UCSBDiningCommonsMenuItemController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-s26/team01-s26-13/pull/52"}]
